### PR TITLE
fix: this package is `commonjs`, align its types correctly

### LINKED ISSUE #324: Incorrect declaration file (import/default)
Eslint-config-prettier has incorrect declaration file: https://github.com/prettier/eslint-config-prettier/pull/294/files (v10.0.3)

Error affects the rule: https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/default.md

Result:
`No default export found in imported module "eslint-config-prettier/flat"  import/default`

### PR DESCRIPTION
**Pull request by pilikan**
fix #324

----

> [!IMPORTANT]
> Fix TypeScript declaration files to properly declare and export `eslintConfigPrettier` and its properties.
> 
>   - **TypeScript Declarations**:
>     - In `flat.d.ts`, replace `export *` with `import` and declare `eslintConfigPrettierFlat` with `name` property.
>     - In `index.d.ts`, declare `eslintConfigPrettier` with `rules` property and export it.
> 
> <sup>This description was created by </sup>[Ellipsis](https://www.ellipsis.dev?ref=prettier%2Feslint-config-prettier&utm_source=github&utm_medium=referral)<sup> for 5904d1ae9c662387cc4d358cf46ee7513938ebcd. You can [customize](https://app.ellipsis.dev/prettier/settings/summaries) this summary. It will automatically update as commits are pushed.</sup>

## Summary by CodeRabbit

- **Refactor**
  - Updated TypeScript declarations to improve export consistency and alignment with CommonJS module usage, enhancing type safety and clarity for developers.

### CODE REVIEW

File: flat.d.ts [hunk 1]
```diff
@@ -1,3 +1,7 @@
-export * from "./index.js";
+import eslintConfigPrettier from "./index.js";
 
-export const name: "config-prettier";
+declare const eslintConfigPrettierFlat: typeof eslintConfigPrettier & {
+  name: "config-prettier";
+};
+
+export = eslintConfigPrettierFlat;
```
Comment (JounQin) [inline flat.d.ts:7]:
```suggestion
export = eslintConfigPrettierFlat;

```

File: index.d.ts [hunk 2]
```diff
@@ -1 +1,5 @@
-export const rules: Record<string, 0 | "off">;
+declare const eslintConfigPrettier: {
+    rules: Record<string, 0 | "off">;
+  };
+  
+export = eslintConfigPrettier;
```
Comment (JounQin) [inline index.d.ts:5]:
```suggestion
export = eslintConfigPrettier;

```

**Review by JounQin — CHANGES_REQUESTED** [review]

**Review by JounQin — APPROVED** [review]

**Comment by JounQin** [comment]
@pilikan Thanks for your contribution! And please use GitHub keywords like `close`, `fix`, etc. in the PR description and follow the conventional commit message next time, see also
- https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests
- https://www.conventionalcommits.org
